---
# tasks file for app-tier
- name: install {{ package }}
  yum:
    name: "{{ package }}"
    state: latest

- name: Enable service {{ package }}
  service:
    name: "{{ package }}"
    enabled: yes

- name: create {{ package }} directory
  file:
    path: "{{ tomcat_webroot }}"
    state: directory

- name: apply static index.html to {{ package }}
  template:
    src: index.html.j2
    dest: "{{ tomcat_webroot }}/index.html"
    mode: 0644

- name: restart {{ package }}
  service:
    name: "{{ package }}"
    state: restarted
